name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Host runner
    container:
      image: alpine:edge # Runs inside an Alpine linux container - edge for Node.js 22
    concurrency: # Prevent overlapping runs
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4 # Fetch the code from the repo
      
      - name: Install Git, Node.js and npm # Git is not on Alpine by default 
        run: apk add --no-cache git nodejs=>22 npm

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      
      - name: Install and build
        run: npm install && npm run build
      
      - name: Verify build 
        run: ls -la ./dist || exit 1 # Vite outputs to ./dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          publish_dir: ./dist
          
